#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh
#
# Copyright 2002-2013 Red Hat, Inc.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -E
set -e

usage() {
    echo "Usage: `basename $0` [-v] [--mkinitrd] [--rminitrd] [--dracut]" >&2
    echo "       [--initrdfile=<initrd-image>] [--depmod] [--rmmoddep]" >&2
    echo "       [--kernel-args=<args>] [--remove-args=<args>]" >&2
    echo "       [--make-default] [--add-dracut-args]" >&2
    echo "       [--add-plymouth-initrd]" >&2
    echo "       [--host-only]" >&2
    echo "       <--install | --remove | --update | --rpmposttrans> <kernel-version>" >&2
    echo "       (ex: `basename $0` --mkinitrd --depmod --install 2.4.7-2)" >&2
    exit 1
}

checkarch()
{
    ARCH="$(uname -m | sed s,i[3456789]86,ia32,)"
    case $1 in
    $ARCH)
        return 0
        ;;
    *)
        exit 0
        ;;
    esac
}

checkcfg()
{
    [ -e $1 ] && return 0
    exit 0
}

is_defined_function()
{
    declare -F $1 >/dev/null 2>&1
}

should_use_multiboot()
{
    if is_defined_function use_multiboot ; then
        use_multiboot
        return $?
    fi
    return 0
}

depmod()
{
    local version="$1"

    [ -n "$verbose" ] && echo "running depmod for $version"
    depmod -ae -F /boot/System.map-$version $version
}

rmdepmod()
{
    local version="$1"

    [ -n "$verbose" ] && echo "removing modules.dep info for $version"
    if [ -d /lib/modules/$version ]; then
        rm -f /lib/modules/$version/modules.*.bin \
            /lib/modules/$version/modules.{alias,dep,devname,symbols,softdep}
    fi
}

mkramfs()
{
    local version="$1"
    local bootprefix=/boot
    if is_defined_function get_boot_prefix ; then
        bootprefix="$(get_boot_prefix)"
    fi
    initrdfile="$bootprefix/$initramfs-$version"

    tool="dracut $dracuthostonly -f $initrdfile $version"
    [ -n "$verbose" ] && echo "creating initramfs: $tool"
    $tool
}

rmramfs()
{
    local version="$1"
    local bootprefix=/boot
    if is_defined_function get_boot_prefix ; then
        bootprefix="$(get_boot_prefix)"
    fi
    initrdfile="$bootprefix/initramfs-$version"

    [ -n "$verbose" ] && echo "removing initrd $initrdfile"
    [ -f $initrdfile ] && rm -f $initrdfile
}

default_get_title()
{
    local version="$1"

    local title=""
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        title="$NAME ($version) $VERSION"
    elif [ -f /etc/redhat-release ]; then
        title="$(sed 's/ release.*$//' < /etc/redhat-release) ($version)"
    else
        title="Red Hat Linux ($version)"
    fi
    echo $title
}

default_get_kernel_args()
{
    local kernargs=""
    # add dracut i18n, keyboard and plymouth kernel args if requested
    if [ -r /etc/vconsole.conf ]; then
        . /etc/vconsole.conf
    elif  [ -r /etc/sysconfig/keyboard ]; then
        . /etc/sysconfig/keyboard
    fi

    if [ -r /etc/locale.conf ]; then
        . /etc/locale.conf
    elif [ -r /etc/sysconfig/i18n ]; then
        . /etc/sysconfig/i18n
    fi

    for i in SYSFONT SYSFONTACM UNIMAP LANG KEYTABLE; do
        val=$(eval echo \$$i)
        [ -n "$val" ] && kernargs="$kernargs $i=$val"
    done

    if [ -n "$KEYBOARDTYPE" -a "$KEYBOARDTYPE" != "pc" ]; then
         kernargs="$kernargs KEYBOARDTYPE=$KEYBOARDTYPE"
    fi
    echo $kernargs
}

default_add()
{
    local version="$1"

    local package="kernel"
    [[ "$2" == *\+* ]] && package="kernel-${2##*+}"
    local kernelimage="$2"

    if [ -z "$kernelimage" ]; then
        local kernelname=vmlinuz
        if is_defined_function get_kernel_name ; then
            kernelname="$(get_kernel_name)"
        fi
        
        local bootprefix=/boot
        if is_defined_function get_boot_prefix ; then
            bootprefix="$(get_boot_prefix)"
        fi
        kernelimage="$bootprefix/$kernelname-$version"
    fi

    local MBK=""
    local MBA=""
    if should_use_multiboot ; then
        MBK=${mbkernel:+--add-multiboot="$mbkernel"}
        MBA=${mbargs:+--mbargs="$mbargs"}
    fi

    local config=${configfile:+-c "$configfile"}  

    local title=""
    if is_defined_function get_title ; then
        title="$(get_title $version)"
    else
        title="$(default_get_title $version)"
    fi

    local rootdevice=""
    if is_defined_function get_root_device ; then
        rootdevice="$(get_root_device)"
    else
        rootdevice="$(default_get_root_device)"
    fi

    local extraargs=""
    if is_defined_function get_loader_specific_args ; then
        extraargs="$(get_loader_specific_args)"
    fi

    local makedefault=""
    if [ "$UPDATEDEFAULT" == "yes" -a -n "$package" -a -n "$DEFAULTKERNEL" -a \
            "$package" == "$DEFAULTKERNEL" ]; then
        makedefault="--make-default"
    fi

    local kernelargs=""
    if is_defined_function get_kernel_args ; then
        kernelargs="$(get_kernel_args)"
    else
        kernelargs="$(default_get_kernel_args)"
    fi

    grubby $loader $config $extraargs --add-kernel="$kernelimage" \
        --title "$title" --package="$package" --copy-default $makedefault \
        $MBK $MBA --args="root=$rootdevice $kernelargs" \
        --remove-kernel="TITLE=$title"
}

default_remove()
{
    local version="$1"
    local kernelimage="$2"

    local files
    local f
    files="/etc/kernel/prerm.d/*[^~] /etc/kernel/prerm.d/$version/*[^~]"
    for f in $files ; do
        [ -f $f ] && [ -x $f ] || continue
        $f $version $kernelimage
    done

    local config=${configfile:+-c "$configfile"}  

    local extraargs=""
    if is_defined_function get_loader_specific_args ; then
        extraargs="$(get_loader_specific_args)"
    fi

    grubby $loader $config $extraargs --remove-kernel="$kernelimage"
}

default_addramfs()
{
    local version="$1"

    local bootprefix=/boot
    if is_defined_function get_boot_prefix ; then
        bootprefix="$(get_boot_prefix)"
    fi
    initrdfile="$bootprefix/initramfs-$version"

    INITRD="--initrd $initrdfile"
    if [ -n "$extraramfs" ]; then
        INITRD="$INITRD --extra-initrd $bootprefix/$extraramfs"
    fi

    grubby $loader $config $extraargs --update-kernel="$kernelimage" \
        $INITRD
}

default_finalize()
{
    local version="$1"
    local kernelimage="$2"

    local files
    local f
    files="/etc/kernel/postinst.d/*[^~] /etc/kernel/postinst.d/$version/*[^~]"
    for f in $files ; do
        [ -f $f ] && [ -x $f ] || continue
        $f $version $kernelimage
    done
}

[ -f /etc/sysconfig/kernel ] && . /etc/sysconfig/kernel

mbkernel="$HYPERVISOR"
mbargs="$HYPERVISOR_ARGS"
extraramfs="$EXTRA_RAMFS"
dracuthostonly=""
loader=""
configfile=""
verbose=""

if [ "$HOSTONLY_INITRAMFS" == "true" ]; then
    dracuthostonly="-H"
fi

main()
{
    mode=""
    version=""
    kernelimage=""

    while [ $# -gt 0 ]; do
        case $1 in
        --configfile*)
            if [[ $1 == --configfile\=* ]]; then
                configfile=${1#--configfile=}
            else
                configfile=$2
                shift
            fi
            ;;
        --loader*)
            if [[ $1 ==--loader\=* ]]; then
                loader=${1#--loader=}
            else
                loader=$2
                shift
            fi
            ;;
        -v|--verbose)
            verbose=-v
            ;;
        *)
            if [ -z "$mode" ]; then
                mode="$1"
            elif [ -z "$version" ]; then
                version="$1"
            elif [ -z "$kernelimage" ]; then
                kernelimage="$1"
            else
                usage >&2
                exit 1
            fi
            ;;
        esac
        shift
    done

    export configfile dracuthostonly extraramfs loader mbargs mbkernel verbose

    case "$mode" in
    --install|--add|add)
        if is_defined_function add ; then
            add "$version" "$kernelimage"
        else
            default_add "$version" "$kernelimage"
        fi
        ;;
    --remove|remove)
        rmdepmod "$version" "$kernelimage"
        rmramfs "$version" "$kernelimage"
        if is_defined_function remove ; then
            remove "$version" "$kernelimage"
        else
            default_remove "$version" "$kernelimage"
        fi
        ;;
    --addramfs|addramfs)
        depmod "$version" "$kernelimage"
        mkramfs "$version" "$kernelimage"
        if is_defined_function addramfs ; then
            addramfs "$version" "$kernelimage"
        else
            default_addramfs "$version" "$kernelimage"
        fi
        ;;
    --rpmposttrans|--finalize|finalize)
        if is_defined_function finalize ; then
            finalize "$version" "$kernelimage"
        else
            default_finalize "$version" "$kernelimage"
        fi
        ;;
    esac
}
